version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: SoloFit
    restart: always
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=SoloFit_Database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 999:3306